INSERT INTO TAG (TAG_WORD) VALUES ('JavaScript');
INSERT INTO TAG (TAG_WORD) VALUES ('Java');
INSERT INTO TAG (TAG_WORD) VALUES ('SQL');
INSERT INTO TAG (TAG_WORD) VALUES ('Spring');
INSERT INTO TAG (TAG_WORD) VALUES ('React');
INSERT INTO TAG (TAG_WORD) VALUES ('C');
INSERT INTO TAG (TAG_WORD) VALUES ('C++');
INSERT INTO MEMBER (NICKNAME) VALUES ('orangetree');