# 서버 환경에서 사용하는 정보들은 application-server.yml 파일에 설정
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop  # (1) 스키마 자동 생성 create(-drop) vs none
#      ddl-auto: create
#      ddl-auto: update
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      #      schema-locations: classpath:db/schema.sql
      data-locations: classpath:data.sql
      mode: always
  datasource:
    url: jdbc:mysql://preproject36-database.czxx2zbzxpwu.ap-northeast-2.rds.amazonaws.com:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC # ?autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: prepro36
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    converters:
      preferred-json-mapper: gson

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: kevin123412341234123412341234123412341234123412341234 # 민감한 정보는 시스템 환경 변수에서 로드 ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

#config:
#  domain: {AWS S3 Endpoint}

#server:
#  port: 8080
#  address: 13.209.255.107