spring:
  jpa:
    hibernate:
#      ddl-auto: create-drop  # (1) 스키마 자동 생성 create(-drop) vs none
      ddl-auto: create
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    defer-datasource-initialization: true
  sql:
    init:
      #      schema-locations: classpath:db/schema.sql
      data-locations: classpath:data.sql
      mode: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: dud741
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true
    username: root



  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    converters:
      preferred-json-mapper: gson